### ISSUE TITLE
Create some way for people to submit proposals

### ISSUE THREAD

**Issue by mw44118** [216software/heights-code-hop#11]
We use symposion (https://github.com/pinax/symposion) for PyOhio, and it's OK, but I don't feel like setting it all up right now.

Any ideas on how to collect proposals?

**Comment by ajm188** [comment]
I was thinking people could just open an issue here, or maybe a PR?

**Comment by mw44118** [comment]
I like this idea -- just submit an issue for each talk.  Then we don't need
to do any work.

Probably should write some instructions in the HTML page showing how to do
this.

On Thu, Dec 24, 2015 at 9:42 PM, Andrew Mason notifications@github.com
wrote:

> I was thinking people could just open an issue here, or maybe a PR?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/216software/heights-code-hop/issues/11#issuecomment-167180994
> .

## 

W. Matthew Wilson
partner
216 Software, LLC
matt@216software.com
http://216software.com

**Comment by mw44118** [comment]
A friend just told me about B-side CLE.  That's a mini-conference at the B-Side Lounge.

On their website, they use a google form:

https://bsidescle.com/call-for-papers/

I like this because it seems less intimidating than asking people to make github issues.

**Comment by jrgifford** [comment]
:+1: on that - something else is that it makes rejection less embarrassing for first-time presenters. it’s less public, so people are more likely to try it.

**Comment by ajm188** [comment]
Agreed with all that. But now we would need to determine who gets access to the proposals to discuss which get approved.

**Comment by mw44118** [comment]
Anybody want to volunteer to learn about google forms?  I think that all
the data gets dumped into a google spreadsheet that we can choose who
accesses.

On Tue, Jan 19, 2016 at 12:42 PM, Andrew Mason notifications@github.com
wrote:

> Agreed with all that. But now we would need to determine who gets access
> to the proposals to discuss which get approved.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/216software/heights-code-hop/issues/11#issuecomment-172929685
> .

## 

W. Matthew Wilson
partner
216 Software, LLC
matt@216software.com
http://216software.com

**Comment by ajm188** [comment]
Yep, that's exactly how it works.

**Comment by mw44118** [comment]
OK, I made a google form: https://docs.google.com/forms/d/1Kft9AmUEaXU2psuwVDzyEzU0itcpzN7rMWIRTrkqsqo/viewform?usp=send_form

Can y'all give it a try?

**Comment by mw44118** [comment]
A friend tested it out and it seems to work fine.
