### ISSUE TITLE
Set up a website

### ISSUE THREAD

**Issue by mw44118** [216software/heights-code-hop#2]
First draft of site is up here:  http://heights-code-hop.org

On that website, we need:
-   Describe what kind of talks we're looking for
-   Offer some way to submit a talk proposal
-   Describe where the venue is and when it is
-   Later, list the scheduled talks
-   Describe who should show up.  Emphasize beginners are welcome.
-   Offer a way for people to sponsor.  Figure out what we need sponsorship for.  Food?  Coffee?

**Comment by adriennefriend** [comment]
I have some experience writing sponsorship levels! Is the conference one or two day, and will it be free for attendees?

**Comment by mw44118** [comment]
Excellent questions!  I have no idea.  I would prefer to keep it free, and
probably do it all on one Saturday.  At least for the first year.

What do you think about free vs paid, and one day vs two days?

I'm hoping that if we use the library for space, and tell people to pack a
lunch, then we don't need to mess with collecting money.  Of course if a
sponsor wants to provide drinks and snacks, that would be great.

**Comment by adriennefriend** [comment]
I definitely think we could keep it free, with the right sponsorship levels. Would be great to provide for attendees:

Light breakfast
Coffee service - AM
Lunch
Coffee service - PM
Dismiss

Also, instead of doing a full two-day event, you could do a welcome talk and sprints on the evening before (encourage people to come to this!!!!! say this is when you pick up swag and do registration) and then have the full day of talks the day following.

**Comment by adriennefriend** [comment]
The library sounds lovely! Do they have a space where you can bring in food/catering, and are they generally cool with it?

**Comment by mw44118** [comment]
I'll double-check if the library tolerates food and drinks in their meeting
rooms.

They have this page that describes their policies:

http://meetings.heightslibrary.org/meeting-rooms/faqs/

I like the idea of optional night-before stuff!  However, I want to keep
this almost too small at first.  Just an extra-special meet-up really, for
people that don't normally go to conferences, because maybe they're high
school kids, or have family commitments, or whatever.

**Comment by mw44118** [comment]
OK, site is up!  http://heights-code-hop.org

Now to move on to getting talks.

**Comment by ajm188** [comment]
I think there may be a DNS issue...my browser is redirecting to 216software.github.io/heights-code-hop

**Comment by mw44118** [comment]
Not a DNS issue -- I set up A DNS forward because I'm just that lazy :)

**Comment by mw44118** [comment]
Closing for now.

The HTML for the website is in the gh-pages branch of this repository.  If you want to tweak it, just send a pull request.

**Comment by ajm188** [comment]
@mw44118 Can we get a link to the website on the repo? Up at the top with the description
