### ISSUE TITLE
Pick a code of conduct

### ISSUE THREAD

**Issue by mw44118** [216software/heights-code-hop#4]
Emphasize that there will be people there of all ages, so content should be G-rated!

This is not the place for raunchy jokes.

**Comment by smcabrera** [comment]
Here's a link to the one I use for a ruby gem that I published. Feel free to steal this or modify it however you like--I didn't come up with it. New ruby gems that are created with the bundler gem automatically have the option to include this Code of Conduct and it seems fine. https://github.com/smcabrera/get_freaky/blob/master/CODE_OF_CONDUCT.md

**Comment by smcabrera** [comment]
For more ideas RubyConf seemed to have a pretty robust code of conduct: http://rubyconf.org/policies

**Comment by ajm188** [comment]
[MLH](http://static.mlh.io/docs/mlh-code-of-conduct.pdf) has a pretty good
one as well.

**Comment by mw44118** [comment]
OK, just reviewed all of those.  Thanks for the links!  I'm reviewing them all now.

How do y'all feel about us taking this one from PyOhio?  I like it because there's a short version and a long version:

http://www.pyohio.org/code-of-conduct/

**Comment by ajm188** [comment]
Looks good to me. :+1:

**Comment by mw44118** [comment]
CoC is up on the site.  Here's to hoping people are well-behaved!
