### ISSUE TITLE
After we have a date and venue, set up eventbrite for registration

### ISSUE THREAD

**Issue by mw44118** [216software/heights-code-hop#5]
We've used Eventbrite for PyOhio, and as far as I know, it's free for free events.

Maybe there's a better option out there?

I set up an eventbrite event for 90 people here: https://www.eventbrite.com/e/heights-code-hop-tickets-20156571849

**Comment by jrgifford** [comment]
Techpint uses [nvite](https://nvite.com/).

**Comment by mw44118** [comment]
Both nvite and eventbrite are free if the conference is free.  Am inclined to use eventbrite because I've used it before and it has always worked OK in the past.

Any strong objections?

**Comment by mw44118** [comment]
Eventbrite created: https://www.eventbrite.com/e/heights-code-hop-tickets-20156571849

**Comment by JKobyP** [comment]
It looks like tickets aren't available for sale - are we at capacity, or has the box office not opened yet?

**Comment by mw44118** [comment]
Hey Koby -- thanks for letting me know!  It is fixed now.  Eventbrite
closed the window of tickets being for sale on Feb 29th.

Matt
